apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-frontend-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/himansusekharsahoo/ecom-infra.git
    targetRevision: main
    path: helm/ecom-frontend
    helm:
      releaseName: ecom-frontend
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
